/**:
  ros__parameters:
    output_dir: /ros2_ws/src/grover_bridge/json_dumps
    mqtt:
      broker_ip: "192.168.1.100"
      broker_port: 1883
      keepalive: 60
      topics:
        - "grover/cam_rig/metadata"
